# Generated by Django 5.0.1 on 2024-01-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_weekwisedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthWiseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('stk', models.IntegerField()),
            ],
        ),
    ]
