# Generated by Django 5.0.1 on 2024-01-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_monthwisedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthwisedata',
            name='stk',
            field=models.FloatField(),
        ),
    ]
