# Generated by Django 5.0.1 on 2024-01-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_monthwisedata_stk'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekWiseDifferenceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_diff', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('stk', models.IntegerField()),
            ],
        ),
    ]
