# Generated by Django 5.0.1 on 2024-01-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_weekwisedifferencedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('stk', models.FloatField()),
            ],
        ),
    ]
