# Generated by Django 5.0.1 on 2024-01-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_summerdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggDataWeekMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_month', models.IntegerField()),
                ('avg', models.FloatField()),
                ('minimum', models.IntegerField()),
                ('maximum', models.IntegerField()),
                ('data_2023', models.IntegerField()),
            ],
        ),
    ]
