# Generated by Django 5.0.1 on 2024-01-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_aggdataweekmonth'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthwiseBuildDraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('curr_month_stk', models.FloatField()),
                ('prev_month_stk', models.FloatField()),
                ('build_or_draw', models.CharField(max_length=1)),
            ],
        ),
    ]
