# Generated by Django 5.0.1 on 2024-01-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_monthwisebuilddraw'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearwiseBuildDraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('stk', models.IntegerField()),
                ('diff', models.FloatField()),
            ],
        ),
    ]
