# Generated by Django 5.0.1 on 2024-01-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_yearwisebuilddraw'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildDrawPercentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('build_per', models.FloatField()),
                ('draw_per', models.FloatField()),
            ],
        ),
    ]
