# Generated by Django 5.0.1 on 2024-01-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_builddrawpercentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PercentageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('spr_per', models.FloatField()),
                ('gas_per', models.FloatField()),
                ('dist_per', models.FloatField()),
            ],
        ),
    ]
