# Generated by Django 5.0.1 on 2024-01-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_percentagedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='percentagedata',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
