# Generated by Django 5.0.1 on 2024-01-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_percentageyearly'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildDrawPercentageWeekly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('build_per', models.FloatField()),
                ('draw_per', models.FloatField()),
            ],
        ),
    ]
