# Generated by Django 5.0.1 on 2024-01-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_builddrawpercentageweekly'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildDrawHeatmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('build_draw', models.IntegerField()),
            ],
        ),
    ]
